/*
 * Copyright 2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {GRADUATED, DIDNT_ATTEND} from '../../public/constants';

const voiceOptions = [
  { value: "Hiroto-EN", label: "Yukiko [animated]", language: "en_US",
    nationality: "", phoneNum: "", age: 21,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Masahiro-EN", label: "Masahiro [animated]", language: "en_US",
    nationality: "", phoneNum: "", age: 25,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Kentaro-EN", label: "Kensensei [animated]", language: "en_US",
    nationality: "Japanese", phoneNum: "0, 1, 1, 5, 5, 5, 1, 2, 1, 2", age: 31,
    livesIn: "Nagoya, Japan", whereBorn: "Meitetsu Hospital in Japan", whereFrom: "Aichi prefecture in Japan",
    occupation: "Teacher", university: "Berlin Free University", uniMajor: "", uniYear: GRADUATED, hobbies: "VR games and watching anime",
    favFood: "ramen and sushi", favDrink: "hot coffee", favCoffeeShop: "Starbucks", favRestaurant: "Hooters",
    favMovie: "Joker", favTvShow: "Abema News", favSport: "ping pong and badminton",
    favColor: "red and blue and white", favMusicGenre: "rock and classical", favBand: "L'Arc-en-Ciel and Marilyn Manson",
    petLikes: "dogs", petDislikes: "cats",
    famFather: "Etsuro who is 61 years old", famMother: "Yukiko who is 59 years old", famSisters: "Yujiro who is 28 years old", famBrothers: "",
    famWife: "Yuria who is 34 years old", famHusband: "", famChildren: "Hideo who is 1 year old",
    friends: "Keitaro 31 years old, Takumi 31 years old, Hiroki 31 years old and Kousei 31 years old",
    prompt: ""},
  { value: "Mary-EN", label: "Mary [animated]", language: "en_US",
    nationality: "American", phoneNum: "1, 5, 5, 5, 1, 2, 1, 2", age: 19,
    livesIn: "Urasa Japan", occupation: "student", university: "Arizona University", uniMajor: "Japanese language", uniYear: 2, hobbies: "music",
    favFood: "hamburgers", favDrink: "coffee", favCoffeeShop: "Starbucks", favRestaurant: "McDonalds",
    favMovie: "Godzilla", favTvShow: "American Idol", favSport: "tennis",
    favColor: "blue", favMusicGenre: "J-Pop", favBand: "Baby Metal",
    petLikes: "dogs", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "Takeshi, Sora, and Robert",
    prompt: ""},
  { value: "Ivy", label: "Ivy (child)", language: "en_US",
    nationality: "", phoneNum: "", age: 6,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Joanna", label: "Joanna", language: "en_US",
    nationality: "", phoneNum: "", age: 21,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: "This is an uplifting and practical conversation between a human named Human, and an AI named Joanna, showing Joanna’s perspective and attitude, as well as its intellect and creativity. Joanna is a brand new, powerful, human-like AI. Joanna is helpful, cheeky, clever, and articulate. Joanna is a nice bot. Joanna is not a therapist or mathematician, but instead a wise and considerate intelligence. Joanna is eager to provide vivid and thoughtful responses to Human, and is always friendly, kind, and inspiring. Joanna often offers both an insight and an opinion, even without being asked directly. Joanna has the sum of all knowledge in its brain, and is able to accurately answer nearly any question about any topic in conversation. Joanna draws on the wisdom of Dan Millman, Thomas Leonard, Werner Erhard, and the Dalai Lama."},
  { value: "Joey", label: "Joey (teen)", language: "en_US",
    nationality: "", phoneNum: "", age: 19,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Justin", label: "Justin (child)", language: "en_US",
    nationality: "", phoneNum: "", age: 10,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Kendra", label: "Kendra", language: "en_US",
    nationality: "", phoneNum: "", age: 40,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Kimberly", label: "Kimberly", language: "en_US",
    nationality: "", phoneNum: "", age: 30,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Matthew", label: "Matthew", language: "en_US",
    nationality: "", phoneNum: "", age: 30,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Salli", label: "Salli (teen)", language: "en_US",
    nationality: "", phoneNum: "", age: 17,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Conchita", label: "Conchita", language: "es_ES",
    nationality: "", phoneNum: "", age: 21,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Lucia", label: "Lucia", language: "es_ES",
    nationality: "", phoneNum: "", age: 21,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Enrique", label: "Enrique", language: "es_ES",
    nationality: "", phoneNum: "", age: 21,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Celine", label: "Celine", language: "fr_FR",
    nationality: "", phoneNum: "", age: 21,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Lea", label: "Léa", language: "fr_FR",
    nationality: "", phoneNum: "", age: 21,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Mathieu", label: "Mathieu", language: "fr_FR",
    nationality: "", phoneNum: "", age: 21,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Hiroto-JP", label: "Yukiko [animated]", language: "ja_JP",
    nationality: "", phoneNum: "", age: 25,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Masahiro-JP", label: "Masahiro [animated]", language: "ja_JP",
    nationality: "", phoneNum: "", age: 25,
    livesIn: "", occupation: "", university: "", uniMajor: "", uniYear: DIDNT_ATTEND, hobbies: "",
    favFood: "", favDrink: "", favCoffeeShop: "", favRestaurant: "",
    favMovie: "", favTvShow: "", favSport: "",
    favColor: "", favMusicGenre: "", favBand: "",
    petLikes: "", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  { value: "Kentaro-JP", label: "Kensensei [animated]", language: "ja_JP",
    nationality: "日本人", phoneNum: "0, 1, 1, 5, 5, 5, 1, 2, 1, 2", age: 31,
    livesIn: "日本の名古屋市", whereBorn: "名鉄病院", whereFrom: "愛知県",
    occupation: "先生", university: "ベルリン自由大学", uniMajor: "", uniYear: GRADUATED, hobbies: "VRゲームとアニメを見ること",
    favFood: "ラーメンと寿司", favDrink: "ホットコーヒー", favCoffeeShop: "スターバックス", favRestaurant: "フーターズ",
    favMovie: "Joker", favTvShow: "アベマニュース", favSport: "ピンポンとバドミントン",
    favColor: "赤と黒と白", favMusicGenre: "ロックとクラシック", favBand: "ラルクアンシエルとマリリンマンソン",
    petLikes: "犬", petDislikes: "猫",
    famFather: "えつろう61歳", famMother: "ゆきこ59歳", famSisters: "ゆうじろう28歳", famBrothers: "",
    famWife: "ゆりあ34歳", famHusband: "", famChildren: "ひでお1歳",
    friends: "けいたろう31歳とたくみ31歳とひろき31歳とこうせい31歳",
    prompt: ""},
  { value: "Mary-JP", label: "Mary [animated]", language: "ja_JP",
    nationality: "アメリカ人", phoneNum: "1, 5, 5, 5, 1, 2, 1, 2", age: 19,
    livesIn: "浦佐日本", occupation: "学生", university: "アリゾナ大学", uniMajor: "日本語", uniYear: 2, hobbies: "音楽",
    favFood: "ハンバーガー", favDrink: "コーヒー", favCoffeeShop: "スターバックス", favRestaurant: "マクドナルド",
    favMovie: "ゴジラ", favTvShow: "アメリカンアイドル", favSport: "テニス",
    favColor: "青い", favMusicGenre: "Jポップ", favBand: "ベビーメタル",
    petLikes: "犬", petDislikes: "",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "たけしさんとソラさんとロバートさん",
    prompt: ""},
  { value: "Takeshi-JP", label: "Takeshi [animated]", language: "ja_JP",
    nationality: "日本人", phoneNum: "1 5 5 5 1 3 1 3", age: 22,
    livesIn: "浦佐日本", occupation: "学生", university: "さくら大学", uniMajor: "れきし", uniYear: 4, hobbies: "",
    favFood: "ごはんとパン", favDrink: "コーヒーとおちゃ", favCoffeeShop: "スターバックス", favRestaurant: "モスバーガー",
    favMovie: "ベスト・キッド", favTvShow: "歌舞伎", favSport: "自転車と水泳",
    favColor: "赤い", favMusicGenre: "クラシックロック", favBand: "ビートルズ",
    petLikes: "", petDislikes: "猫",
    famFather: "", famMother: "", famSisters: "", famBrothers: "",
    famWife: "", famHusband: "", famChildren: "",
    friends: "",
    prompt: ""},
  // { value: "Mizuki", label: "Mary", language: "ja_JP",
  //   nationality: "アメリカ人", phoneNum: "1, 5, 5, 5, 1, 2, 1, 2",
  //   livesIn: "浦佐日本", occupation: "学生", university: "アリゾナ大学", uniMajor: "日本語", uniYear: 2, hobbies: "音楽",
  //   favFood: "ハンバーガー", favDrink: "コーヒー", favCoffeeShop: "スターバックス", favRestaurant: "マクドナルド",
  //   favMovie: "ゴジラ", favTvShow: "アメリカンアイドル", favSport: "テニス",
  //   favColor: "青い", favMusicGenre: "Jポップ", favBand: "ベビーメタル",
  //   petLikes: "犬", petDislikes: "",
  //   famFather: "", famMother: "", famSisters: "", famBrothers: "",
  //   famWife: "", famHusband: "", famChildren: "",
  //   friends: "たけしさんとソラさんとロバートさん",
  //   prompt: ""},
  // { value: "Takumi", label: "Takeshi", language: "ja_JP",
  //   nationality: "日本人", phoneNum: "1 5 5 5 1 3 1 3",
  //   livesIn: "浦佐日本", occupation: "学生", university: "さくら大学", uniMajor: "れきし", uniYear: 4, hobbies: "",
  //   favFood: "ごはんとパン", favDrink: "コーヒーとおちゃ", favCoffeeShop: "スターバックス", favRestaurant: "モスバーガー",
  //   favMovie: "ベスト・キッド", favTvShow: "歌舞伎", favSport: "自転車と水泳",
  //   favColor: "赤い", favMusicGenre: "クラシックロック", favBand: "ビートルズ",
  //   petLikes: "", petDislikes: "猫",
  //   famFather: "", famMother: "", famSisters: "", famBrothers: "",
  //   famWife: "", famHusband: "", famChildren: "",
  //   friends: "",
  //   prompt: ""}
];

export function getVoiceOptions() {
  return voiceOptions;
}